/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as MechanicsRouteImport } from './routes/mechanics'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthDebugRouteImport } from './routes/auth-debug'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const MechanicsRoute = MechanicsRouteImport.update({
  id: '/mechanics',
  path: '/mechanics',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDebugRoute = AuthDebugRouteImport.update({
  id: '/auth-debug',
  path: '/auth-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth-debug': typeof AuthDebugRoute
  '/dashboard': typeof DashboardRoute
  '/logout': typeof LogoutRoute
  '/mechanics': typeof MechanicsRoute
  '/payment': typeof PaymentRoute
  '/register': typeof RegisterRoute
  '/success': typeof SuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth-debug': typeof AuthDebugRoute
  '/dashboard': typeof DashboardRoute
  '/logout': typeof LogoutRoute
  '/mechanics': typeof MechanicsRoute
  '/payment': typeof PaymentRoute
  '/register': typeof RegisterRoute
  '/success': typeof SuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth-debug': typeof AuthDebugRoute
  '/dashboard': typeof DashboardRoute
  '/logout': typeof LogoutRoute
  '/mechanics': typeof MechanicsRoute
  '/payment': typeof PaymentRoute
  '/register': typeof RegisterRoute
  '/success': typeof SuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth-debug'
    | '/dashboard'
    | '/logout'
    | '/mechanics'
    | '/payment'
    | '/register'
    | '/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth-debug'
    | '/dashboard'
    | '/logout'
    | '/mechanics'
    | '/payment'
    | '/register'
    | '/success'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth-debug'
    | '/dashboard'
    | '/logout'
    | '/mechanics'
    | '/payment'
    | '/register'
    | '/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthDebugRoute: typeof AuthDebugRoute
  DashboardRoute: typeof DashboardRoute
  LogoutRoute: typeof LogoutRoute
  MechanicsRoute: typeof MechanicsRoute
  PaymentRoute: typeof PaymentRoute
  RegisterRoute: typeof RegisterRoute
  SuccessRoute: typeof SuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mechanics': {
      id: '/mechanics'
      path: '/mechanics'
      fullPath: '/mechanics'
      preLoaderRoute: typeof MechanicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-debug': {
      id: '/auth-debug'
      path: '/auth-debug'
      fullPath: '/auth-debug'
      preLoaderRoute: typeof AuthDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthDebugRoute: AuthDebugRoute,
  DashboardRoute: DashboardRoute,
  LogoutRoute: LogoutRoute,
  MechanicsRoute: MechanicsRoute,
  PaymentRoute: PaymentRoute,
  RegisterRoute: RegisterRoute,
  SuccessRoute: SuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
